import Background from '@/component/Background'
import Footer from '@/component/Footer'
import NavBar from '@/component/NavBar'
import ClientCookiesProvider from '@/cookie'
import ReduxProvider from '@/stores'
import {
  AcademicCapIcon,
  BriefcaseIcon,
  DocumentTextIcon,
  NewspaperIcon,
  UserIcon
} from '@heroicons/react/24/solid'
import React from 'react'
import type { Metadata } from 'next'
import { Noto_Sans_TC } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'

const noto = Noto_Sans_TC({
  weight: ['400', '500', '800'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const routes = [
  { name: 'About', href: '/about', icon: <UserIcon className="w-4 h-4" /> },
  {
    name: 'Education',
    href: '/education',
    icon: <AcademicCapIcon className="w-4 h-4" />
  },
  { name: 'Work', href: '/work', icon: <BriefcaseIcon className="w-4 h-4" /> },
  {
    name: 'Articles',
    href: '/articles',
    icon: <NewspaperIcon className="w-4 h-4" />
  },
  {
    name: 'Publications',
    href: '/publications',
    icon: <DocumentTextIcon className="w-4 h-4" />
  }
]

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const theme = cookies().get('theme')
  return (
    <ReduxProvider>
      <ClientCookiesProvider value={cookies().getAll()}>
        <html lang="en" data-theme={theme ? theme.value : 'light'}>
          <head>
            <title>{`I'm Jim`}</title>
          </head>
          <body className={`${noto.className} bg-base-300`}>
            <Background />
            <div className="relative w-full min-h-[100dvh] h-fit">
              <NavBar routes={routes} />
              {children}
              <Footer routes={routes} />
            </div>
          </body>
        </html>
      </ClientCookiesProvider>
    </ReduxProvider>
  )
}
